version: '3.7'
services:
  app:
    build:
      context: .
    image: graphicsearch:latest
    command: ["uvicorn", "app:app", "--host=0", "--log-level=trace", "--use-colors", "--reload"]
    ports:
      - '127.0.0.1:${PORT:-8000}:8000'
    volumes:
      - ./app:/app
  elasticsearch:
    image: elasticsearch:7.5.1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node
volumes:
  es-data:
    driver: local
