version: '3.7'
services:
  app:
    image: graphicsearch:latest
    ports:
      - '5000:5000'
  elasticsearch:
    image: elasticsearch:7.5.0
    ports:
      - '9200:9200'
    volumes:
      - es-data:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node
volumes:
  es-data:
    driver: local
