version: '3.7'
services:
  app:
    build:
      context: .
      target: development
    image: graphicsearch-dev:latest
    ports:
      - '5000:5000'
    volumes:
      - ./app:/app
  elasticsearch:
    image: elasticsearch:7.5.1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node
volumes:
  es-data:
    driver: local
